/*
 * Copyright (c) 2022 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#pragma once

#define CHIP_CONFIG_CONTROLLER_MAX_ACTIVE_DEVICES 2
/* Three dynamic endpoints: the lock's vendor cluster (src/lock_cluster.cpp),
 * the battery (src/battery.cpp) and the button itself (src/switch_cluster.cpp).
 * Without this, MAX_ENDPOINT_COUNT stays equal to the number of fixed endpoints
 * and emberAfSetDynamicEndpoint has nowhere to put them. */
#define CHIP_DEVICE_CONFIG_DYNAMIC_ENDPOINT_COUNT 3

/* The version the device reports, without the build-metadata tail.
 *
 * NCS binds SoftwareVersionString to APP_VERSION_EXTENDED_STRING, which is
 * "3.0.6+0" - major.minor.patch plus the VERSION file's tweak, appended even
 * when it is zero, which it always is here. Nothing reads that zero and every
 * screen showing a firmware version had to carry it.
 *
 * This is set as the CONFIG_ symbol rather than the CHIP_ one on purpose. This
 * header is included BEFORE the platform config (CHIPDeviceConfig.h, project at
 * line 41 and platform at 53), so defining the CHIP_ macro here would simply be
 * overwritten a few lines later. The platform config picks its value with
 *
 *     #ifdef CONFIG_CHIP_DEVICE_SOFTWARE_VERSION_STRING
 *
 * and that symbol does not otherwise exist: its Kconfig is declared inside
 * `if "$(APPVERSION)"==""`, so having a VERSION file removes it. Defining it
 * here fills the hole the SDK already checks for, and nothing is redefined.
 *
 * APP_VERSION_STRING is generated by Zephyr from the same VERSION file - so
 * this stays correct when the version changes, which a literal would not.
 */
#include "app_version.h"
#define CONFIG_CHIP_DEVICE_SOFTWARE_VERSION_STRING APP_VERSION_STRING


